### ISSUE TITLE
Hide menu if no visualization gets rendered

### ISSUE THREAD

**Issue by mhebing** [ddionrails/ddionrails-visualization#15]
Einbau hat soweit erst mal gut funktioniert, nur ein kleines Problem hab ich gerade: Das Menü wird ja jetzt unabhängig von der Grafik bereits im HTML angelegt. Wenn ich jetzt aber auf eine Variable gehe, für die keine Visualisierung zur Verfügung steht, dann ist aber halt trotzdem das Menü zu sehen.

Ich hab dem Menü jetzt `id="vis_menu"` zugeordnet. Mit jQuery kann man es dann einfach verstecken: `$("#vis_menu).hide()`. Nur weiß ich leider nicht, wo man das im `render.js` ausführen muss…

Könntest Du das bitte noch an den passenden Stellen einbauen?

**Comment by castolpe** [comment]
@mhebing  Kann man denn an einem fehlenden Attribut feststellen (z. B. keine Skala), dass es keine Visualisierung geben wird?

**Comment by mhebing** [comment]
Stimmt, das wäre wohl am einfachsten. :smile:  Prüf doch einfach, ob `uni` vorhanden ist…
